[package]
name = "ironplc-parser"
version = "0.1.0"
description = "Parser for IEC 61131 code."
authors = [ "Garret Fick" ]
edition = "2021"

[dependencies]
time = "0.3.11"
ironplc-dsl = { path = "../dsl" }

[dependencies.peg]
version = "0.8.0"
features = ["trace"]
