on:
  push:
    tags:        
      - '*'
  schedule:
      - cron: '0 19 * * *'
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

name: Publish IronPLC Releases

jobs:
  release:
    name: Create GitHub Release
    # Only needs to run on one platform because this is defining
    # the container for the release rather than building the artifacts
    runs-on: ubuntu-latest
    
    outputs:
      release_id: ${{ steps.create_release.outputs.automatic_release_tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'schedule'
      - uses: actions/checkout@v3
        if: github.event_name == 'workflow_dispatch'
      
      # The tag depends on whether the this ran because a tag was creates
      # of it this was a scheduled release.
      - name: Create Tag
        id: create_tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            tag=v$(date +%Y%m%d.%H%M%S)
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag=${{ inputs.release_tag }}
          else
            tag=$(basename "${{ github.ref }}")
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        env:
          GITHUB_TOKEN: 
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.create_tag.outputs.tag }}
          draft: true
          prerelease: false
    
  build-win:
    name: Build Windows Installer
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        name: [ release ]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Rust tests
        # Only runs the unit tests - we don't care here about formatting
        # or other things because we are building the release
        run: cargo test --all-features

      - name: Install cargo-wix tool
        run: cargo install cargo-wix

      # Assumes the wix toolkit is available.
      - name: Create installer
        run: cargo wix -v --nocapture -o ./ironplc-${{ matrix.name }}-windows.msi -p ironplcc

      - name: Update Windows Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ironplc-${{ matrix.name }}-windows.msi
          asset_name: iconplc-${{ matrix.name }}-windows.msi
          asset_content_type: application/octet-stream

  cleanup:
    name: Cleanup Old Development Releases
    needs: [release, build-win]
    runs-on: ubuntu-latest
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.release.outputs.release_id }}
      - uses: eregon/keep-last-n-releases@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 3
          remove_tags_without_release: true